versions = [
# renovate: datasource=github-tags depName=rfjakob/earlyoom
    "v1.8.2",
]

# renovate: datasource=docker
base_image = "ghcr.io/anza-labs/library/distroless/musl:latest"

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
