versions = [
    "latest",
]

arch = [
    "amd64",
    "arm64",
    "ppc64le",
    "riscv64",
]

base_image = "scratch"

targets = [
    "static",
    "static-rootless",
    "musl",
    "musl-rootless",
]
