versions = [
# renovate: datasource=github-tags depName=skarnet/nsss versioning=loose
    "v0.2.1.0",
]

# renovate: datasource=docker
base_image = "ghcr.io/anza-labs/library/distroless/musl:latest"

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
