versions = [
# renovate: datasource=git-refs packageName=https://github.com/u-root/u-root currentValue=main
    "9b0bdb8329dbcdc8de9e98c9c21a998ada19f8cc",
]

# renovate: datasource=docker
base_image = "gcr.io/distroless/static:latest@sha256:47b2d72ff90843eb8a768b5c2f89b40741843b639d065b9b937b07cd59b479c6"

arch = [
    "amd64",
    "arm64",
    "ppc64le",
    "riscv64",
]
