versions = [
# renovate: datasource=git-refs packageName=https://github.com/u-root/u-root currentValue=main
    "7d751bfc0612a2c7b7e20a5f5712267a02ab4e15",
]

# renovate: datasource=docker
base_image = "gcr.io/distroless/static:latest@sha256:47b2d72ff90843eb8a768b5c2f89b40741843b639d065b9b937b07cd59b479c6"

arch = [
    "amd64",
    "arm64",
    "ppc64le",
    "riscv64",
]
