versions = [
# renovate+git: datasource=git-refs depName=u-root packageName=https://github.com/u-root/u-root
    "c2b9e48e151e8efeab13029a9bcf9236eae176ca",
]

arch = [
    "amd64",
    "arm64",
    "ppc64le",
    "riscv64",
]
