use = "docker"

[labels]
    "org.opencontainers.image.authors" = "anza-labs contributors"
    "org.opencontainers.image.vendor" = "anza-labs"
    "org.opencontainers.image.source" = "https://github.com/anza-labs/docker-library"
    "org.opencontainers.image.created" = "${{ github.event.created_at }}"
    "org.opencontainers.image.url" = "${{ github.event.repository.html_url }}"
    "org.opencontainers.image.revision" = "${{ github.sha }}"

[registry]
    name = "ghcr.io"
    repository = "anza-labs"
    username = "shanduur-auto"

[workflow]
    prefix = "gen_"

[engine.buildah]
    build = [ "bud" ]
    push = [ "push" ]

    [engine.buildah.manifest]
    create = [ "manifest", "create", "--amend" ]
    annotate = [ "manifest", "annotate" ]
    push = [ "manifest", "push" ]

[engine.docker]
    build = [ "buildx", "build", "--load" ]
    push = [ "push" ]

    [engine.docker.manifest]
    create = [ "manifest", "create", "--amend" ]
    annotate = [ "manifest", "annotate" ]
    push = [ "manifest", "push" ]

[engine.podman]
    build = [ "build" ]
    push = [ "push" ]

    [engine.podman.manifest]
    create = [ "manifest", "create", "--amend" ]
    annotate = [ "manifest", "annotate" ]
    push = [ "manifest", "push" ]
