versions = [
# renovate: datasource=github-tags depName=minio/mc versioning=regex:^RELEASE\.?(?<major>\d+)-(?<minor>\d+)-(?<patch>\d+)(.+)?$
    "RELEASE.2025-07-21T05-28-08Z",
]

arch = [
    "amd64",
    "arm64",
    "ppc64le",
]
