versions = [
# renovate: datasource=github-tags depName=odin-lang/Odin versioning=loose
    "dev-2026-05",
]

# renovate: datasource=docker
base_image = "docker.io/library/alpine:3.23.4@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659"

arch = [
    "amd64",
    "arm64",
]
