apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 20
containerRuntimeEndpoint: "unix:///var/run/crio/crio.sock"
cgroupDriver: cgroupfs
failSwapOn: false
authentication:
    webhook:
        enabled: false
