versions = [
# renovate: datasource=github-tags depName=Mirantis/cri-dockerd
    "v0.3.18",
]

# renovate: datasource=docker
base_image = "ghcr.io/anza-labs/library/distroless/static:latest"

arch = [
    "amd64",
    "arm64",
]
