versions = [
# renovate: datasource=github-tags depName=chainguard-dev/kaniko
    "v1.25.15",
]

# renovate: datasource=docker
base_image = "gcr.io/distroless/static:latest@sha256:47b2d72ff90843eb8a768b5c2f89b40741843b639d065b9b937b07cd59b479c6"

arch = [
    "amd64",
    "arm64",
]

targets = [
    "executor",
    "executor-debug",
    "warmer",
]
