name: template

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: actionCheckout
        uses: actions/checkout@v5
      - id: actionSetupQEMU
        uses: docker/setup-qemu-action@v3
      - id: actionDockerLogin
        uses: docker/login-action@v3
      - id: actionSetupBuildx
        uses: docker/setup-buildx-action@v3
      - id: actionCosignInstaller
        uses: sigstore/cosign-installer@v4.0.0
