versions = [ 
# renovate: datasource=github-tags depName=kubernetes/kubernetes
    "v1.32.0",
# renovate: datasource=github-tags depName=kubernetes/kubernetes
    "v1.33.0",
]

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
