versions = [ 
# renovate: datasource=github-tags depName=kubernetes/kubernetes
    "v1.34.0",
]

# renovate: datasource=docker
base_image = "docker.io/library/golang:1.24-alpine"

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
