versions = [ 
# renovate: datasource=github-tags depName=kubernetes/kubernetes
    "v1.33.3",
]

# renovate: datasource=docker
base_image = "docker.io/library/golang:1.24"

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
