versions = [
# renovate: datasource=repology depName=homebrew/bc versioning=loose
    "1.08.2",
]

# renovate: datasource=docker
base_image = "ghcr.io/anza-labs/library/distroless/musl:latest"

arch = [
    "amd64",
    "arm64",
    "riscv64",
]
