name: release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'library/**/version.txt'

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: extract
        run: |
          ./hack/version-change.sh "${GITHUB_OUTPUT}"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: shanduur-auto
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/anza-labs/library/${{ steps.extract.outputs.project }},enable=true
          tags: |
            type=semver,pattern={{version}},value=${{ steps.extract.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.extract.outputs.version }}
            type=sha
      - run: |
          echo "variable \"${{ steps.extract.outputs.project }}\" { default = \"${{ steps.extract.outputs.version }}\" }" > ./vars.hcl
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
            cwd://vars.hcl
          targets: ${{ steps.extract.outputs.project }}
