name: release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'library/**/version.txt'

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract project and version
        id: extract
        run: |
          ./hack/version-change.sh
      - uses: docker/setup-qemu-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ inputs.registry || 'ghcr.io' }}/${{ inputs.repository || 'anza-labs/library' }}/${{ env.project }},enable=true
          tags: |
            type=semver,pattern={{version}},value=${{ env.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.version }}
            type=sha
      - run: |
          echo "variable \"${{ env.project }}\" { default = \"${{ env.version }}\" }" > ./vars.hcl
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ inputs.push }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
            cwd://vars.hcl
          targets: ${{ env.project }}
