name: autorelease

on:
  push:
    branches:
      - 'main'
    paths:
      - 'library/**/Dockerfile'

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ghcr.io/anza-labs/library
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: extract
        run: |
          ./hack/version-change.sh "${REPOSITORY}"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: shanduur-auto
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - run: |
          ./release.sh
