jobs:
  build:
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              buildx \
              build \
              --load \
              --label=org.opencontainers.image.authors='anza-labs contributors' \
              --label=org.opencontainers.image.created='${{ github.event.created_at }}' \
              --label=org.opencontainers.image.revision='${{ github.sha }}' \
              --label=org.opencontainers.image.source='https://github.com/anza-labs/docker-library' \
              --label=org.opencontainers.image.url='${{ github.event.repository.html_url }}' \
              --label=org.opencontainers.image.vendor='anza-labs' \
              --target=${{ matrix.target }} \
              --build-arg=VERSION=${{ matrix.version }} \
              --build-arg=BASE_IMAGE=ghcr.io/anza-labs/library/distroless/static:latest \
              --platform=linux/${{ matrix.arch }} \
              --file=library/go-busybox/Dockerfile \
              --tag=ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-${{ matrix.arch }} \
              library/go-busybox
      - run: |-
          docker \
              push \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-${{ matrix.arch }}
      - uses: sigstore/cosign-installer@v4.0.0
      - if: ${{ matrix.version != 'latest' }}
        run: |-
          cosign \
              sign \
              --yes \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - ppc64le
          - riscv64
        target:
          - image
        version:
          - c2b9e48e151e8efeab13029a9bcf9236eae176ca
  promote:
    env: {}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              manifest \
              create \
              --amend \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }} \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-amd64 \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-arm64 \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-ppc64le \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              annotate \
              --arch=amd64 \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }} \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-amd64 && \
          docker \
              manifest \
              annotate \
              --arch=arm64 \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }} \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-arm64 && \
          docker \
              manifest \
              annotate \
              --arch=ppc64le \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }} \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-ppc64le && \
          docker \
              manifest \
              annotate \
              --arch=riscv64 \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }} \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              push \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}
      - uses: sigstore/cosign-installer@v4.0.0
      - if: ${{ matrix.version != 'latest' }}
        run: |-
          cosign \
              sign \
              --yes \
              ghcr.io/anza-labs/library/go-busybox:${{ matrix.version }}
    strategy:
      matrix:
        target:
          - image
        version:
          - c2b9e48e151e8efeab13029a9bcf9236eae176ca
name: release library/go-busybox
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/gen__library_go-busybox.yaml
      - library/go-busybox/Dockerfile
      - library/go-busybox/pkg.toml
  workflow_dispatch: {}
permissions:
  contents: write
  id-token: write
  packages: write
