jobs:
  build:
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              buildx \
              build \
              --load \
              --target=${{ matrix.target }} \
              --build-arg=VERSION=${{ matrix.version }} \
              --platform=linux/${{ matrix.arch }} \
              --file=library/amber/Dockerfile \
              --tag=ghcr.io/anza-labs/library/amber:${{ matrix.version }}-${{ matrix.arch }} \
              library/amber
      - run: |-
          docker \
              push \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - amd64
        target:
          - image
        version:
          - 0.4.0-alpha
  promote:
    env: {}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              manifest \
              create \
              --amend \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }} \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }}-amd64
      - run: |-
          docker \
              manifest \
              annotate \
              --arch=amd64 \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }} \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }}-amd64
      - run: |-
          docker \
              manifest \
              push \
              ghcr.io/anza-labs/library/amber:${{ matrix.version }}
    strategy:
      matrix:
        target:
          - image
        version:
          - 0.4.0-alpha
name: release library/amber
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/gen__library_amber.yaml
      - library/amber/Dockerfile
  workflow_dispatch: {}
permissions:
  contents: write
  packages: write
