jobs:
  build:
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              buildx \
              build \
              --load \
              --label=org.opencontainers.image.authors='anza-labs contributors' \
              --label=org.opencontainers.image.created='${{ github.event.created_at }}' \
              --label=org.opencontainers.image.revision='${{ github.sha }}' \
              --label=org.opencontainers.image.source='https://github.com/anza-labs/docker-library' \
              --label=org.opencontainers.image.url='${{ github.event.repository.html_url }}' \
              --label=org.opencontainers.image.vendor='anza-labs' \
              --target=${{ matrix.target }} \
              --build-arg=VERSION=${{ matrix.version }} \
              --build-arg=BASE_IMAGE=ghcr.io/anza-labs/library/distroless/static-rootless:latest \
              --platform=linux/${{ matrix.arch }} \
              --file=library/kubernetes/Dockerfile \
              --tag=ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-${{ matrix.arch }} \
              library/kubernetes
      - run: |-
          docker \
              push \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - riscv64
        target:
          - kube-apiserver
          - kube-controller-manager
          - kube-scheduler
          - kube-proxy
          - kubectl
          - kubelet
        version:
          - v1.33.4
  promote:
    env: {}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              manifest \
              create \
              --amend \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }} \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-amd64 \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-arm64 \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              annotate \
              --arch=amd64 \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }} \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-amd64 && \
          docker \
              manifest \
              annotate \
              --arch=arm64 \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }} \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-arm64 && \
          docker \
              manifest \
              annotate \
              --arch=riscv64 \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }} \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              push \
              ghcr.io/anza-labs/library/kubernetes/${{ matrix.target }}:${{ matrix.version }}
    strategy:
      matrix:
        target:
          - kube-apiserver
          - kube-controller-manager
          - kube-scheduler
          - kube-proxy
          - kubectl
          - kubelet
        version:
          - v1.33.4
name: release library/kubernetes
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/gen__library_kubernetes.yaml
      - library/kubernetes/Dockerfile
  workflow_dispatch: {}
permissions:
  contents: write
  packages: write
