jobs:
  build:
    env: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              buildx \
              build \
              --load \
              --target=${{ matrix.target }} \
              --build-arg=VERSION=${{ matrix.version }} \
              --platform=linux/${{ matrix.arch }} \
              --file=library/bc/Dockerfile \
              --tag=ghcr.io/anza-labs/library/bc:${{ matrix.version }}-${{ matrix.arch }} \
              library/bc
      - run: |-
          docker \
              push \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - riscv64
        target:
          - image
        version:
          - 1.08.2
  promote:
    env: {}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: shanduur-auto
      - uses: docker/setup-buildx-action@v3
      - run: |-
          docker \
              manifest \
              create \
              --amend \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }} \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-amd64 \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-arm64 \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              annotate \
              --arch=amd64 \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }} \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-amd64 && \
          docker \
              manifest \
              annotate \
              --arch=arm64 \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }} \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-arm64 && \
          docker \
              manifest \
              annotate \
              --arch=riscv64 \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }} \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}-riscv64
      - run: |-
          docker \
              manifest \
              push \
              ghcr.io/anza-labs/library/bc:${{ matrix.version }}
    strategy:
      matrix:
        target:
          - image
        version:
          - 1.08.2
name: release library/bc
"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/gen__library_bc.yaml
      - library/bc/Dockerfile
  workflow_dispatch: {}
permissions:
  contents: write
  packages: write
