name: release

on:
  push:
    tags:
      - 'zig/v*'

permissions:
  contents: write
  packages: write

jobs:
  zig:
    env:
      ZIG_VERSION: "0.13.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le
      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          context: "./zig"
          build-args: |
            ZIG_VERSION=${{ env.ZIG_VERSION }}
          tags: |
            ghcr.io/anza-labs/docker-zig:${{ env.ZIG_VERSION }}
