name: release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Image name'
        required: true
        type: choice
        options:
        - cloud-provider-kind
        - firecracker
        - go-busybox
        - kine
        - mc
        - zig
      version:
        description: 'Version'
        required: true
        type: string
      push:
        description: 'Push'
        type: boolean
        default: false
      registry:
        description: 'Registry'
        type: string
        default: 'ghcr.io'
      repository:
        description: 'Repository'
        type: string
        default: 'anza-labs/library'

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - run: |
          ./hack/generate-release-script.sh \
            'release.sh' \
            "${{ inputs.registry }}/${{ inputs.repository }}" \
            'docker' \
            'buildx build --load' \
            "" \
            "${{ inputs.name }}" \
            "${{ inputs.version }}" \
            "$(sed -n 's/^# platforms=\(.*\)$/\1/p' ./library/${{ inputs.name }}/Dockerfile)"
      - run: |
          ./release.sh
