name: release

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  zig:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: 
          - "alpine:3.20"
          - "alpine:3.21"
          - "debian:11.11"
          - "debian:12.8"
        zig:
          - "0.12.0"
          - "0.13.0"
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le
      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          context: "{{defaultContext}}:zig"
          build-args: |
            BASE_VERSION=${{ matrix.base }}
          tags: |
            ghcr.io/anza-labs/docker-zig:${{ matrix.zig }}-${{ matrix.base }}
