name: release

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to release'
        required: true
        type: choice
        options:
        - kine
        - zig
      version:
        description: 'version to release'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          context: "./${{ inputs.image }}"
          build-args: |
            VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/anza-labs/library/${{ inputs.image }}:${{ inputs.version }}
